<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\Voucher;

class VoucherSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $vouchers = [
            // === Vouchers theo Membership ===
            [
                'voucher_code' => 'ThanhVienHangDong',
                'voucher_name' => 'Giảm 50,000đ',
                'requirement_price' => 200000,
                'reduced_amount' => 50000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 100,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'membership',
                'membership_id' => 1,
            ],
            [
                'voucher_code' => 'ThanhVienHangBac',
                'voucher_name' => 'Giảm 150,000đ',
                'requirement_price' => 300000,
                'reduced_amount' => 150000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 100,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'membership',
                'membership_id' => 2,
            ],
            [
                'voucher_code' => 'ThanhVienHangVang',
                'voucher_name' => 'Giảm 200,000đ',
                'requirement_price' => 400000,
                'reduced_amount' => 200000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 100,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'membership',
                'membership_id' => 3,
            ],
            [
                'voucher_code' => 'ThanhVienHangKimCuong',
                'voucher_name' => 'Giảm 250,000đ',
                'requirement_price' => 500000,
                'reduced_amount' => 250000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 100,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'membership',
                'membership_id' => 4,
            ],

            // === Vouchers chung (manual) ===
            [
                'voucher_code' => 'Giam10KManual',
                'voucher_name' => 'Giảm 10,000đ đơn từ 100,000đ',
                'requirement_price' => 100000,
                'reduced_amount' => 10000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(15),
                'voucher_status' => 'active',
                'quantity' => 200,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'Giam15PercentManual',
                'voucher_name' => 'Giảm 15%',
                'requirement_price' => 0,
                'reduced_amount' => 15,
                'voucher_type' => 'percent',
                'expired_at' => $now->copy()->addDays(20),
                'voucher_status' => 'active',
                'max_discount_amount' => 30000,
                'quantity' => 150,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'Giam50KManual',
                'voucher_name' => 'Giảm 50,000đ đơn từ 300,000đ',
                'requirement_price' => 300000,
                'reduced_amount' => 50000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(25),
                'voucher_status' => 'active',
                'quantity' => 100,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'FreeshipManual',
                'voucher_name' => 'Freeship đơn từ 200,000đ',
                'requirement_price' => 200000,
                'reduced_amount' => 30000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(10),
                'voucher_status' => 'active',
                'quantity' => 300,
                'usage_per_user' => 1,
                'voucher_scope' => 'shipping',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],

            // === Vouchers đổi điểm ===
            [
                'voucher_code' => 'PointGiam20K',
                'voucher_name' => 'Đổi 100 điểm nhận voucher 20,000đ',
                'requirement_price' => 50000,
                'reduced_amount' => 20000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 200,
                'usage_per_user' => 2,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => true,
                'required_points' => 100,
                'issued_by' => 'point',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'PointGiam10Percent',
                'voucher_name' => 'Đổi 150 điểm nhận voucher giảm 10%',
                'requirement_price' => 0,
                'reduced_amount' => 10,
                'voucher_type' => 'percent',
                'expired_at' => $now->copy()->addDays(20),
                'voucher_status' => 'active',
                'max_discount_amount' => 50000,
                'quantity' => 150,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => true,
                'required_points' => 150,
                'issued_by' => 'point',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'PointGiamFreeship',
                'voucher_name' => 'Đổi 50 điểm nhận voucher Freeship',
                'requirement_price' => 0,
                'reduced_amount' => 30000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(15),
                'voucher_status' => 'active',
                'quantity' => 300,
                'usage_per_user' => 2,
                'voucher_scope' => 'shipping',
                'start_at' => $now,
                'is_redeemable' => true,
                'required_points' => 50,
                'issued_by' => 'point',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'PointGiam100K',
                'voucher_name' => 'Đổi 300 điểm giảm 100,000đ',
                'requirement_price' => 400000,
                'reduced_amount' => 100000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 100,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => true,
                'required_points' => 300,
                'issued_by' => 'point',
                'membership_id' => null,
            ],
            // === Vouchers dành cho Prize Vòng Quay ===
            [
                'voucher_code' => 'Prize_TaiLoc202',
                'voucher_name' => 'Voucher Tài Lộc 202 - Giảm 202,000đ',
                'requirement_price' => 300000,
                'reduced_amount' => 202000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 10,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'Prize_MX224',
                'voucher_name' => 'Voucher MX 224 - Giảm 224,000đ',
                'requirement_price' => 300000,
                'reduced_amount' => 224000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 8,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'Prize_FreeShip',
                'voucher_name' => 'Voucher Freeship - Trị giá 30,000đ',
                'requirement_price' => 200000,
                'reduced_amount' => 30000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(15),
                'voucher_status' => 'active',
                'quantity' => 9,
                'usage_per_user' => 1,
                'voucher_scope' => 'shipping',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'Prize_Giam300K',
                'voucher_name' => 'Voucher Giảm 300K',
                'requirement_price' => 500000,
                'reduced_amount' => 300000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 9,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'Prize_TangBM',
                'voucher_name' => 'Voucher Tặng BM - Giảm 50,000đ',
                'requirement_price' => 200000,
                'reduced_amount' => 50000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 9,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'Prize_Sach15',
                'voucher_name' => 'Voucher Sách -15%',
                'requirement_price' => 0,
                'reduced_amount' => 15,
                'voucher_type' => 'percent',
                'max_discount_amount' => 50000,
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 10,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],
            [
                'voucher_code' => 'Prize_New100K',
                'voucher_name' => 'Voucher New User - Giảm 100,000đ',
                'requirement_price' => 400000,
                'reduced_amount' => 100000,
                'voucher_type' => 'amount',
                'expired_at' => $now->copy()->addDays(30),
                'voucher_status' => 'active',
                'quantity' => 9,
                'usage_per_user' => 1,
                'voucher_scope' => 'global',
                'start_at' => $now,
                'is_redeemable' => false,
                'required_points' => null,
                'issued_by' => 'manual',
                'membership_id' => null,
            ],

        ];

        foreach ($vouchers as $voucher) {
            Voucher::create($voucher);
        }
    }
}
